version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - containedctx
    #- contextcheck
    - depguard
    - errcheck
    - errchkjson
    #- errname
    - errorlint
    #- gochecknoinits
    #- goconst
    - gocritic
    #- gocyclo
    #- godot
    - gosec
    - govet
    - ineffassign
    #- lll
    - loggercheck
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - thelper
    #- tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    depguard:
      rules:
        prevent_kubernetes_dependency:
          list-mode: lax # allow unless explicitly denied
          deny:
            - pkg: k8s.io/kubernetes
              desc: do not use k8s.io/kubernetes directly
    errcheck:
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      check-error-free-encoding: true
    gocritic:
      disabled-checks:
        - appendAssign
        - appendCombine
        - commentedOutCode
        - equalFold
        - exposedSyncMutex
        - httpNoBody
        - hugeParam
        - ifElseChain
        - importShadow
        - methodExprCall
        - nestingReduce
        - preferStringWriter
        - rangeValCopy
        - singleCaseSwitch
        - stringConcatSimplify
        - unlabelStmt
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G110
        - G115
        - G204
        - G306
    lll:
      line-length: 150
  exclusions:
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: test/*
      - linters:
          - errcheck
        source: flags.Parse|response.WriteError
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/weaveworks)
        - Prefix(github.com/weaveworks/weave-gitops)
    gofumpt:
      extra-rules: true
