brews:
  - tap:
      owner: weaveworks
      name: homebrew-tap
    commit_author:
      name: weave-gitops-bot
      email: weave-gitops-bot@weave.works
    folder: Formula
    homepage: "https://docs.gitops.weave.works/docs/getting-started"
    description: "GitOps support for Kubernetes"
    install: |
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
