project_name: gitops
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  prerelease: auto
archives:
  - format: tar.gz
    name_template: >-
      gitops-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
builds:
  - <<: &build_defaults
      binary: "gitops"
      main: ./cmd/gitops
      ldflags:
        - -X github.com/weaveworks/weave-gitops/cmd/gitops/version.Branch={{ .Env.BRANCH}}
        - -X github.com/weaveworks/weave-gitops/cmd/gitops/version.BuildTime={{.Date}}
        - -X github.com/weaveworks/weave-gitops/cmd/gitops/version.GitCommit={{.Commit}}
        - -X github.com/weaveworks/weave-gitops/cmd/gitops/version.Version={{.Version}}
        - -X github.com/weaveworks/weave-gitops/pkg/version.FluxVersion={{ .Env.FLUX_VERSION }}
        - -X github.com/weaveworks/weave-gitops/pkg/analytics.Tier=oss
        - -X github.com/weaveworks/weave-gitops/core/server.Branch={{ .Env.BRANCH}}
        - -X github.com/weaveworks/weave-gitops/core/server.BuildTime={{.Date}}
        - -X github.com/weaveworks/weave-gitops/core/server.GitCommit={{.Commit}}
        - -X github.com/weaveworks/weave-gitops/core/server.Version={{.Version}}
        - -X github.com/weaveworks/weave-gitops/cmd/gitops/beta/run.HelmChartVersion={{ .Env.CHART_VERSION }}
      env:
        - CGO_ENABLED=0
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
  - <<: *build_defaults
    id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
