{
 "title": "explorer",
 "description": "weave gitops explorer metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{handler=\"/v1/query\"}[1m])) by (code)",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{code=\"200\",handler=\"/v1/query\",method=\"POST\"}[1m])) / sum(rate(http_request_duration_seconds_count{code=\"200\",handler=\"/v1/query\",method=\"POST\"}[1m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{handler=\"/v1/query\", code=~\"5..\"}[1m]))",
     "legendFormat": "Traffic"
    }
   ]
  }
 ]
}