{
 "title": "Explorer",
 "description": "weave gitops explorer metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/v1/query\", code=\"200\"}[30m])) * 100 / sum(rate(http_request_duration_seconds_count{handler=\"/v1/query\"}[30m]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Query Requests Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/v1/query\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/v1/query\",code!~\"2..\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Query Requests Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{code=\"200\",handler=\"/v1/query\",method=\"POST\"}[1m])) / sum(rate(http_request_duration_seconds_count{code=\"200\",handler=\"/v1/query\",method=\"POST\"}[1m]))",
     "legendFormat": "200s"
    }
   ]
  },
  {
   "title": "Datastore Read Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(datastore_latency_seconds_count{action=~\"Get.*\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Datastore Read Requests Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(datastore_latency_seconds_sum{action=~\"Get.*\",status=\"success\"}[1m])) / sum(rate(datastore_latency_seconds_count{action=~\"Get.*\",status=\"success\"}[1m]))\n",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Indexer Read Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(indexer_latency_seconds_count[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Indexer Read Requests Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_latency_seconds_sum{status=\"success\"}[1m])) / sum(rate(indexer_latency_seconds_count{status=\"success\"}[1m]))\n",
     "legendFormat": "success"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Objects Cluster Watchers ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collector_cluster_watcher{collector=\"objects\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RBAC Cluster Watchers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collector_cluster_watcher{collector=\"roles\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Datastore Writes Request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(datastore_latency_seconds_count{action=~\"Store.*\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Datastore Write Requests Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(datastore_latency_seconds_sum{action=~\"Store.*\",status=\"success\"}[1m])) / sum(rate(datastore_latency_seconds_count{action=~\"Store.*\",status=\"success\"}[1m]))\n",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Indexer Read Request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(indexer_latency_seconds_count[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Indexer Read Requests Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_latency_seconds_sum{status=\"success\"}[1m])) / sum(rate(indexer_latency_seconds_count{status=\"success\"}[1m]))\n",
     "legendFormat": "success"
    }
   ]
  }
 ]
}