/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introducing GitOps',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'intro',
      },
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'getting-started/intro',
          },
          items: [
            {
              type: 'category',
              label: '0. Install Weave GitOps',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'installation/index',
              },
              items: [
                'installation/weave-gitops',
                {
                  type: 'category',
                  label: 'Weave GitOps Enterprise',
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'installation/weave-gitops-enterprise/index',
                  },
                  items: [
                    'installation/weave-gitops-enterprise/airgap',
                  ],
                },
                'installation/aws-marketplace',
              ],
            },
            'getting-started/ui',
            'getting-started/deploy',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'REFERENCE',
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: 'OSS Helm Reference',
          id: 'references/helm-reference',
        },
        {
          type: 'category',
          label: 'CLI Reference',
          items: [
            {
              type: 'autogenerated',
              dirName: 'references/cli-reference',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Access Configuration',
      items: [
        'configuration/recommended-rbac-configuration',
        {
          type: 'category',
          label: 'Securing Access to the Dashboard',
          collapsed: false,
          link: {
            type: 'doc',
            id:'configuration/securing-access-to-the-dashboard',
          },
          items: [
            'configuration/oidc-access',
            'configuration/emergency-user',
          ],
        },
        'configuration/service-account-permissions',
        'configuration/user-permissions',
        'configuration/tls',
      ],
    },
    {
      type: 'category',
      label: 'GitOps Run',
      link: {
        type: 'doc',
        id: 'gitops-run/overview',
      },
      items: [
        'gitops-run/get-started',
      ],
    },
    {
      type: 'category',
      label: 'Terraform',
      items: [
        'terraform/overview',
        'terraform/get-started',
        {
          type: 'category',
          label: 'Using Terraform CR',
          items: [
            'terraform/using-terraform-cr/provision-resources-and-auto-approve',
            'terraform/using-terraform-cr/plan-and-manually-apply-terraform-resources',
            'terraform/using-terraform-cr/provision-resources-and-write-output-data',
            'terraform/using-terraform-cr/detect-drifts-only-without-plan-or-apply',
            'terraform/using-terraform-cr/drift-detection-disabled',
            'terraform/using-terraform-cr/set-variables-for-trraform-resources',
            'terraform/using-terraform-cr/custom-backend',
            'terraform/using-terraform-cr/depends-on',
            'terraform/using-terraform-cr/modules',
            'terraform/using-terraform-cr/customize-runner',
          ],
        },
        'terraform/backup-and-restore',
        'terraform/oci-artifact',
        'terraform/aws-eks',
        'terraform/terraform-enterprise',
        'terraform/tfctl',
        'terraform/environment-variables',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/setting-up-dex',
        'guides/cert-manager',
        'guides/displaying-custom-metadata',
      ],
    },
    {
      type: 'html',
      value: ' ',
      defaultStyle: true,
    },
    {
      type: 'link',
      label: 'Cluster Management',
      href: '/enterprise/cluster-management/intro'
    },
    {
      type: 'link',
      label: 'Pipelines',
      href: '/enterprise/pipelines/intro'
    },
    {
      type: 'link',
      label: 'Workspaces',
      href: '/enterprise/workspaces/intro'
    },
    {
      type: 'link',
      label: 'Policy',
      href: '/enterprise/policy/intro'
    },
    {
      type: 'link',
      label: 'Templates',
      href: '/enterprise/gitops-templates/intro'
    },
    {
      type: 'link',
      label: 'GitOpsSets',
      href: '/enterprise/gitopssets/intro'
    },
  ],
};
