---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: monitoring
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2-monitoring-example
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: ./monitoring/controllers/kube-prometheus-stack
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: ./monitoring/controllers/loki-stack
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: monitoring
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: ./monitoring/configs
  dependsOn:
    - name: kube-prometheus-stack
  prune: true
