---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 30m0s
  ref:
    branch: master
    tag: '6.6.3'
  url: https://github.com/stefanprodan/podinfo
